jobs:
  tests:
    name: Test App
    runs-on:  ubuntu-latest
    env:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install --upgrade -r requirements.txt
      - run: docker compose up -d --build
      - run: pytest tests

      - run: docker compose logs app
        if: always()
on:
  pull_request:
    branches:
      - main
